version: '3.5'
services: 
    postgres-database:
        restart: always
        image: postgres
        volumes: 
            - pg-database:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=database
        networks: 
            - woowoo_net

volumes: 
    pg-database:
        external: true

networks: 
    woowoo_net:
        external: true
            
    
    