version: '3.5'
services: 
    nginx:
        restart: unless-stopped
        image: nginx
        ports:
          - '80:80'
          - '443:443'
        networks: 
            - woowoo_net

        volumes: 
          - ./nginx.config:/etc/nginx/conf.d/default.conf
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/www:/var/www/certbot
        depends_on:
          - nginx
        networks: 
          - woowoo_net
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"

networks: 
    woowoo_net:
        external: true

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
        
            
    
    